[hbuild]
schema_dir = "schemas"
pkgsrc_dir = "pkgsrc.d"

logs_dir = "logs"

sources_dir = "sources"
tools_dir = "tools"
packages_dir = "packages"
builds_dir = "builds"

patches_dir = "patches"
works_dir="works"

[hbuild.system]
files = "system_files"
prefix = "system_prefix"

[hbuild.system.targets]
x86_64 = "x86_64-hera-linux-gnu"